#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
cd "$PROJECT_DIR"

[[ ${1:-} == -c ]] && { shift; rm -rf .build/virtualenv; }

. ./pactivate -q
exec pytest "$@"
