class BinaryTreeError(Exception): ...
class NodeIndexError(BinaryTreeError): ...
class NodeModifyError(BinaryTreeError): ...
class NodeNotFoundError(BinaryTreeError): ...
class NodeReferenceError(BinaryTreeError): ...
class NodeTypeError(BinaryTreeError): ...
class NodeValueError(BinaryTreeError): ...
class TreeHeightError(BinaryTreeError): ...
